values:
  image:
    tag: "1.4.74"
  ingress:
    className: traefik
    host: sillydemo.127.0.0.1.nip.io
  # autoscaling:
  #   enabled: true
  #   minReplicas: 3
  # db:
  #   enabled: true
  #   provider: "google-official"
